on:
 push :
    branches:
      - main

jobs:
  run_terraform_script:
    name: run terraform script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: change directory 
      run: ls

    - name: pwd
      run: pwd
    
    - name: LS 
      run: ls
