on:
 push :
    branches:
      - main

jobs:
  run terraform script:
    name: run terraform script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: echo 
      run: echo hi blessy please be patient
      working-directory: ./lambda

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_my_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_my_aws_access_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}